artikel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path('tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from .views import (SingupView, SearchView, ArtikelDetail, ArtikelView, UserDetail, 
                    ArtikelViewList, edit, artikelform,ArtikelLike, ArtikelLikeApi,
                    MessageModelViewSet, UserModelViewSet, chat, list_post_tags)
from django.urls import path, include
from .forms import AuthenticatedForm
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter

app_name = "base"

router = DefaultRouter()
router.register(r'message', MessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

urlpatterns = [
    path(r'api/v1/', include(router.urls)),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", form_class=AuthenticatedForm), name="login"),
    path("register/", SingupView.as_view(), name='register'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/<slug:slug>/", UserDetail.as_view(), name="user-detail"),
    path("artikel/<slug:slug>/", ArtikelDetail.as_view(), name="detail-artikel"),
    path("list/", ArtikelViewList.as_view(), name="list-artikel"),
    path("edit/", edit, name="edit"),
    path("create/", artikelform, name="artikel-form"),
    path("search/", SearchView.as_view(), name="search"),
    path("chat/", chat, name="chat"),
    path("", ArtikelView.as_view(), name="home"),
    path("<slug:slug>/like/", ArtikelLike.as_view(), name="like-artikel"),
    path("api/<slug:slug>/like/", ArtikelLikeApi.as_view(), name="like-artikel-api"),
    path("tags/<slug:slug>/", list_post_tags, name="tags-list"),
    path("password/change/", auth_views.PasswordChangeView.as_view(template_name="change_password.html"), name="change_password")
]

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator
from django.db.models import Q
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.db.models.signals import pre_save
from django.contrib.auth.signals import user_logged_in, user_logged_out, user_login_failed
from django.dispatch import receiver
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from .signals import object_viewed_signal
from mirage import fields
import base64

class UserQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(username_user__icontains=query)|Q(email__icontains=query)|Q(bio__icontains=query))
            qs = qs.filter(or_lookup).distinct()
        return qs
class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_field):
        if not email:
            raise ValueError("Harus Menggunakan Email")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_field)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_field):
        extra_field.setdefault("is_staff", False)
        extra_field.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_field)


    def create_superuser(self, email, password=None, **extra_field):
        extra_field.setdefault("is_staff", True)
        extra_field.setdefault("is_superuser", True)
        if extra_field.get("is_staff") is not True:
            raise ValueError(
            "superuser must have is_staff=True"
        )
        if extra_field.get("is_superuser") is not True:
            raise ValueError(
            "superuser must have is_superuser=True"
        )
        return self._create_user(email, password, **extra_field)

    def get_queryset(self):
        return UserQuerySet(self.model, using=self._db)
        
    def search(self, query=None):
        return self.get_queryset().search(query=query)

        

class User(AbstractUser):
    username = None
    username_user = models.CharField(max_length=90, blank=False, null=False)
    image_profile = models.ImageField(upload_to="profile/", null=True, blank=True)
    image_sampul = models.ImageField(upload_to="sampul/", null=True, blank=True)
    email = models.EmailField('email address', unique=True, blank=True, null=False)
    slug = models.SlugField(blank=True, null=True)
    no_tlp = models.IntegerField(validators=[MaxValueValidator(3012)], null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()
    
    def __str__(self):
        return f"{self.email}"
    
    def get_absolute_url(self):
        return reverse("base:user-detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.username_user)
        super(User, self).save(*args, **kwargs)

class Tags(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    bio = models.CharField(max_length=300, blank=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("base:tags-list", kwargs={"slug": self.slug})

    @property
    def all_tags(self):
        return Tags.objects.all()

class ArtikelQuerySet(models.QuerySet):
    def search(self, query=None):
        qs = self
        if query is not None:
            or_lookup = (Q(judul__icontains=query)|Q(isi__icontains=query))
            qs = qs.filter(or_lookup).distinct()
        return qs

class ArtikelManager(models.Manager):
    def get_queryset(self):
        return ArtikelQuerySet(self.model, using=self._db)
    def search(self, query=None):
        return self.get_queryset().search(query=query)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    artikel = models.ForeignKey("Artikel", related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username_user

class Artikel(models.Model):
    judul = models.CharField(max_length=300, blank=False, null=False)
    tags = models.ManyToManyField(Tags, )
    slug = models.SlugField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    isi = models.TextField()
    likes = models.ManyToManyField(User, related_name="likes")
    objects = ArtikelManager()
    media = models.FileField(upload_to="File/")

    def get_like_url(self):
        return reverse("base:like-artikel", kwargs={"slug": self.slug})

    def __str__(self):
        return self.judul
    
    def get_api_like_url(self):
        return reverse("base:like-artikel-api", kwargs={"slug": self.slug})

    def get_absolute_url(self):
        return reverse("base:detail-artikel", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.judul)
        super(Artikel, self).save(*args, **kwargs)

    @property
    def get_comments(self):
        return self.comments.all().order_by('-date_created')

    @property
    def comment_count(self):
        return Comment.objects.filter(artikel=self).count()

    @property
    def artikel_count(self):
        return Artikel.objects.all().count()


class AuditEntry(models.Model):
    action = models.CharField(max_length=64)
    ip = models.GenericIPAddressField(null=True)
    username = models.CharField(max_length=256, null=True)

    def __unicode__(self):
        return '{0} - {1} - {2}'.format(self.action, self.username, self.ip)

    def __str__(self):
        return '{0} - {1} - {2}'.format(self.action, self.username, self.ip)


@receiver(user_logged_in)
def user_logged_in_callback(sender, request, user, **kwargs):  
    ip = request.META.get('REMOTE_ADDR')
    AuditEntry.objects.create(action='user_logged_in', ip=ip, username=user.username_user)


@receiver(user_logged_out)
def user_logged_out_callback(sender, request, user, **kwargs):  
    ip = request.META.get('REMOTE_ADDR')
    AuditEntry.objects.create(action='user_logged_out', ip=ip, username=user.username_user)


@receiver(user_login_failed)
def user_login_failed_callback(sender, credentials, **kwargs):
    AuditEntry.objects.create(action='user_login_failed', username=credentials.get('username_user', None))


class History(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey()
    viewed_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s, %s viewed: %s" %(self.user.username_user, self.content_object, self.viewed_on)

    class Meta:
        verbose_name_plural = "History_User"

def object_viewed_receiver(sender, instance, request, *args, **kwargs):
    new_history = History.objects.create(
        user    = request.user,
        content_type    = ContentType.objects.get_for_model(sender),
        object_id      = instance.id,
    )

object_viewed_signal.connect(object_viewed_receiver)


class MessageModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user',
                      related_name='from_user', db_index=True)
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='recipient',
                           related_name='to_user', db_index=True)
    timestamp = models.DateTimeField('timestamp', auto_now_add=True, editable=False,
                              db_index=True)
    body = fields.EncryptedTextField()
    

    def __str__(self):
        return str(self.user.username_user)


    def notify_ws_clients(self):

        notification = {
            'type': 'recieve_group_message',
            'message': '{}'.format(self.id)
        }

        channel_layer = get_channel_layer()
        print("user.id {}".format(self.user.id))
        print("user.id {}".format(self.recipient.id))

        async_to_sync(channel_layer.group_send)("{}".format(self.user.id), notification)
        async_to_sync(channel_layer.group_send)("{}".format(self.recipient.id), notification)

    def save(self, *args, **kwargs):

        new = self.id
        self.body = self.body.strip()  # Trimming whitespaces from the body
        super(MessageModel, self).save(*args, **kwargs)
        if new is None:
            self.notify_ws_clients()

    # Meta
    class Meta:
        verbose_name = 'message'
        verbose_name_plural = 'messages'
        ordering = ('-timestamp',)

base/forms.py
from django.contrib.auth.forms import (
 UserCreationForm as DjangoUserCreationForm
)
from django.core.mail import send_mail
from django import forms
from django.contrib.auth import authenticate
import logging
from django.contrib.auth.forms import UsernameField
from .models import User, Artikel, Comment
from tinymce.widgets import TinyMCE

logger = logging.getLogger(__name__)


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": UsernameField}
        def send_mail(self):
            logger.info(
            "Sending signup email for email=%s",
            self.cleaned_data["email"],
            )
            message = "Welcome{}".format(self.cleaned_data["email"])
            send_mail(
                "Welcome to Cloudimage",
                message,
                "site@climage.domain",
                [self.cleaned_data["email"]],
                fail_silently=True,
            )


class AuthenticatedForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(strip=False, widget=forms.PasswordInput)

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user = None
        super().__init__(*args, **kwargs)

    def clean(self):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")
        if email is not None and password:
            self.user = authenticate(
                self.request, email=email, password=password
            )
            if self.user is None:
                raise forms.ValidationError(
                "invalid password and email"
            )
            logger.info(
                "Authenticated Success for email=%s", email
            )
        return self.cleaned_data 

    def get_user(self):
        return self.user

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("image_profile", "image_sampul","username_user", "email", "no_tlp", "bio")

        widgets = {
            "username_user": forms.TextInput(attrs={}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
        }


class ArtikelForm(forms.ModelForm):
    class Meta:
        model = Artikel
        fields = ("media" ,"judul", "tags", "isi")
        widgets = {
            "judul": forms.TextInput(attrs={"class": "form-control"}),
            "isi":TinyMCE(attrs={'cols': 80, 'rows':50,'class': 'form-control'})
        }

class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-comment',
        'placeholder': 'Type your comment',
        'id': 'usercomment', 
    }))
    class Meta:
        model = Comment
        fields = ('content', )

base/templates/detail_user.html
{% extends "base.html" %}

{% block title %} Artikel | Detail {% endblock title %}

{% block content %}
<div>
    <div class="w-full max-w-screen-xl mx-auto px-6">
      <div class="lg:flex -mx-6">
        <div class="min-h-screen w-full lg:static lg:max-h-full lg:overflow-visible">
            <div id="content">
                <div class="flex">
                  <div class="pt-24 pb-16 lg:pt-28 lg:ml-16 w-full">
                    <div class="border-b-2 pb-2 w-11/12 flex justify-center">
                      <span class="{% if request.user_detail == 'base:user-detail' %}text-blue-700 font-bold{% endif %}">
                        <a href="" class="pr-24 "><h2>Profile</h2></a>
                      </span>
                      <span class="">
                        <a href="{% url 'base:list-artikel' %}"><h2>Artikel</h2></a>
                      </span>
                        
                    </div>
                    <div class="pt-8 realtive">
                      <img src="{{user_detail.image_sampul.url}}" class="object-cover lg:shadow-xl" style="height: 30rem; width: 69rem; -webkit-filter: brightness(50%); filter: brightness(79%);" alt=""> 
            
                      <div class="absolute " style="top: 15rem; left: 35rem; bottom: 10rem; right: 34rem;">
                        <img src="{{user_detail.image_profile.url }}" class="rounded-full h-32 w-32 object-cover ml-32" alt="">
                        <div class="border-b-2 border-white pb-2 mr-4">
                          <p class="text-3xl text-white font-medium text-center">{{user_detail.username_user}}</p>  
                          <p class="text-xl text-white font-medium text-center">{{user_detail.email}}</p>
                           
                        </div>
                       
                        <div class="flex justify-center">
                          <div class="border-r-2 border-white w-auto inline-block">
                            <p class="text-xl text-white font-medium mr-4 mt-4">Artikel:{{artikel}} </p>
                          </div>
                          <div class="">
                            <p class="text-xl text-white font-medium ml-4 mt-4">View: 200 </p>
                          </div>
                        </div>
                        <div class="mt-2 flex justify-between">
                          
                          <a href="{% url 'base:artikel-form' %}">
                          <button
                                  class="p-0 w-16 h-16 bg-blue-600 rounded-full hover:bg-blue-700 active:shadow-lg mouse shadow transition ease-in duration-200 focus:outline-none">
                            <svg viewBox="0 0 20 20" enable-background="new 0 0 20 20" class="w-6 h-6 inline-block">
                              <path fill="#FFFFFF" d="M16,10c0,0.553-0.048,1-0.601,1H11v4.399C11,15.951,10.553,16,10,16c-0.553,0-1-0.049-1-0.601V11H4.601
                                                      C4.049,11,4,10.553,4,10c0-0.553,0.049-1,0.601-1H9V4.601C9,4.048,9.447,4,10,4c0.553,0,1,0.048,1,0.601V9h4.399
                                                      C15.952,9,16,9.447,16,10z" />
                            </svg>
                          </button>
                        </a>
                          <a href="{% url 'base:edit' %}">
                          <button
                                class="p-0 w-16 h-16 bg-blue-600 rounded-full hover:bg-blue-700 active:shadow-lg mouse shadow transition ease-in duration-200 focus:outline-none">
                                <svg id="Solid" class="w-6 h-6 inline-block" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
                                  <path fill="#FFFFFF" d="m255.997 477.327 47.003-10.847-36.157-36.156z"/>
                                  <path fill="#FFFFFF" d="m246.722 446.363 7.777-33.7c.019-.083.047-.161.069-.242.037-.139.074-.278.118-.415s.088-.252.135-.376.088-.234.138-.349c.059-.137.124-.27.19-.4.049-.1.1-.195.151-.29.077-.14.159-.274.243-.408.054-.085.108-.169.165-.252.092-.134.189-.263.289-.39.061-.079.122-.157.186-.233.1-.123.213-.241.323-.357.045-.047.085-.1.131-.144l104.805-104.807c-29.258-60.181-83.362-96-145.442-96-45.522 0-87.578 19.485-118.421 54.865-31.062 35.633-48.565 85.3-49.536 140.291 18.364 9.261 93.769 44.844 167.957 44.844a298.024 298.024 0 0 0 30.722-1.637z"/><path fill="#FFFFFF" d="m270.461 342.863h176v64h-176z" transform="matrix(.707 -.707 .707 .707 -160.078 363.266)"/><circle fill="#FFFFFF" cx="216" cy="112" r="80"/><path fill="#FFFFFF" d="m464 301.324a32 32 0 0 0 -54.627-22.624l45.254 45.254a31.785 31.785 0 0 0 9.373-22.63z"/></svg>
                        </button>
                        </a>
                        <div class="m-3">
                          <a href="{% url 'base:logout' %}">
                          <button class="bg-white text-gray-800 font-bold rounded border-b-2 border-blue-500 hover:border-blue-600 hover:bg-blue-500 hover:text-white shadow-md py-2 px-6 inline-flex items-center">
                            <span class="mr-2">Sing out</span>
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                             <path fill="currentcolor" d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12 19 6.41z"/>
                            </svg>
                          </button>
                        </a>
                        </div>
                        </div>
                      </div>
                    </div>
                    <div class="border border-white p-4 bg-white" style="width: 90.8888%;">
                      
                    </div>
                  </div>
                
                </div>
                
            </div>
            <div class="lg:flex">
            {% include "include/sidebar_profile.html" %}
            <div>
              {% for artikel in user_detail.artikel_set.all %}
              <div class="grid grid-cols-1 gap-6 px-4 md:px-6 mb-8">
                <div class="max-w-xl mx-24 px-4 py-4 bg-white shadow-md rounded-lg">
                  <div class="py-2 flex flex-row items-center justify-between">
                    <div class="flex flex-row items-center">
                      <a href="#" class="flex flex-row items-center focus:outline-none focus:shadow-outline rounded-lg">
                        <img class="rounded-full h-8 w-8 object-cover" src="{{artikel.user.image_profile.url}}" alt="">
                        <p class="ml-2 text-base font-medium">{{artikel.user.username_user}}</p>
                      </a>
                    </div>
                    <div class="flex flex-row items-center">
                      <p class="text-xs font-semibold text-gray-500">{{artikel.date_created}}</p>
                    </div>
                  </div>
                  <a href="{{artikel.get_absolute_url}}">
                  <div class="mt-2">
                    <img class="object-cover w-full rounded-lg" src="{{artikel.media.url}}" alt="">
                    <div class="py-2 flex flex-row items-center">
                      <a class="like-btn" data-href='{{ artikel.get_api_like_url }}' data-likes='{{ artikel.likes.count }}' href="{{artikel.get_like_url}}">
                      <button class="flex flex-row items-center focus:outline-none focus:shadow-outline rounded-lg">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-5 h-5"><path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
                        <span class="ml-1">{{artikel.likes.count}}</span>
                      </button>
                    </a>
                      <button class="flex flex-row items-center focus:outline-none focus:shadow-outline rounded-lg ml-3">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-5 h-5"><path d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
                        <span class="ml-1">{{artikel.comment_count}}</span>
                      </button>
                      <button class="flex flex-row items-center focus:outline-none focus:shadow-outline rounded-lg ml-3">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" class="w-5 h-5"><path d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"></path></svg>
                        <span class="ml-1">340</span>
                      </button>
                    </div>
                  </div>
                </a>
                  <div class="py-2">
                    <h2 class="font-bold text-2xl text-gray-800 tracking-normal"><a href="{{artikel.get_absolute_url}}">{{artikel.judul}}</a></h2>
                    <p class="leading-snug break-all">{{artikel.isi|truncatewords:50|safe }}</p>
                  </div>
                  <div class="px-6 py-4">
                    {% for tags in artikel.tags.all %}
                    <span class="inline-block bg-blue-400 rounded-full px-3 py-1 text-sm font-semibold text-white mr-2">#{{tags.title}}</span>
                    {% endfor %}
                  </div>
                </div>
                
              </div>
              {% endfor %}
            </div>
          </div>
          </div>
        </div>
    </div>
</div>
{% endblock content %}


base/templates/login.html
{% extends "base.html" %}

{% block title %}Artikel | Login{% endblock title %}

{% block content %}
<div>
    <div class="w-full max-w-screen-xl mx-auto px-6">
      <div class="lg:flex  -mx-6">
        <div class="pt-24 flex justify-center items-center pb-16 lg:pt-28 w-full">
            <div class="w-full max-w-xs">
                <h1 class="text-3xl font-bold text-indigo-800 mb-8 mx-32">Login</h1>
                    <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" method="POST"> {% csrf_token %}
                            <div class="mb-4">
                                <div>
                                    <label class="block text-gray-700 text-sm font-bold mb-2">{{ form.email.label_tag }}</label>
                                    <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline {% if form.email.errors %}is-valid{% endif %}" id="id_email" 
                                    name="email" placeholder="Email" value="{{ form.email.value|default:''}}" />
                                    <div>
                                     {% if form.email.errors %}
                                        <span class='bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative '>{{ form.email.errors}}</span>
                                      {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="mb-6">
                                <div>
                                    <label class="block text-gray-700 text-sm font-bold mb-2">{{ form.password.label_tag }}</label>
                                    <input type="password" name="password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline {% if form.password.errors %}is-valid{% endif %}" id="id_password">
                                    
                                    {% if form.password.errors %}
                                        <div>
                                            {{form.password.errors}}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="flex items-center justify-between">
                            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                                Sign In
                            </button>
                            <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
                                Forgot Password?
                            </a>
                        </div>
                    </form>
                <p style="margin-top: 1rem;">
                    Don't have an account? <Link to='/register'>Register</Link>
                </p>
                <p class="text-center text-gray-500 text-xs">
                    &copy;2020 Acme Corp. All rights reserved.
                </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

base/templates/user_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block title %} Artikel | Edit User {% endblock title %}

{% block content %}
<div>
  <div class="w-full max-w-screen-xl mx-auto px-6">
    <div class="lg:flex -mx-6">
      <div class="w-full lg:static lg:max-h-full">
        <div class="pt-24 pb-16 lg:pt-28 w-full">
          <div class="border-b-2 pb-2 w-11/12 flex justify-center">
            <span class="{% if request.user_detail == 'base:user-detail' %}text-blue-700 font-bold{% endif %}">
              <a href="{% url 'base:artikel-form' %}" class="pr-24 "><h2>Profile</h2></a>
            </span>
            <span class="">
              <a href="{% url 'base:change_password' %}"><h2>Password</h2></a>
            </span>
              
          </div>
          <div class="px-4 py-4 bg-white shadow-md rounded-lg">
                    <p class="text-center text-2xl font-medium my-6 text-gray-400">Edit your profile</p>
                  <form action="" enctype="multipart/form-data" method="post">
                      <div class="text-center">
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Image Sampul</p>{{user_form.image_profile}}
                        </div>
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Image Profile</p>{{user_form.image_sampul}}
                        </div>
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Name</p>{{user_form.username_user|add_class:"form-control"}}
                        </div>
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Email</p>{{user_form.email}}
                        </div>
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Phone Number</p>{{user_form.no_tlp|add_class:"shadow appearance-none border rounded w-1/2 py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline resize-none"}}
                        </div>
                        <div class="mb-4">
                          <p class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2">Biografi</p>{{user_form.bio|add_class:"shadow appearance-none border rounded w-1/2 h-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline resize-none"}}
                        </div>
                      {% csrf_token %}
                      <div class="my-4">
                      <input class="block uppercase mx-auto shadow bg-indigo-800 hover:bg-indigo-700 focus:shadow-outline focus:outline-none text-white text-xs py-3 px-10 rounded" type="submit" value="Save Change">
                    </div>
                  </div>
                    </form>
                </div>
            </div>
          </div>
    </div>
  </div>
</div>

{% endblock content %}