artikel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("base.urls")),
    path('tinymce/', include('tinymce.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from .views import (SingupView, SearchView, ArtikelDetail, ArtikelView, UserDetail, 
                    ArtikelViewList, edit, artikelform,ArtikelLike, ArtikelLikeApi,
                    MessageModelViewSet, UserModelViewSet, chat, list_post_tags)
from django.urls import path, include
from .forms import AuthenticatedForm
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter

app_name = "base"

router = DefaultRouter()
router.register(r'message', MessageModelViewSet, basename='message-api')
router.register(r'user', UserModelViewSet, basename='user-api')

urlpatterns = [
    path(r'api/v1/', include(router.urls)),
    path("login/", auth_views.LoginView.as_view(template_name="login.html", form_class=AuthenticatedForm), name="login"),
    path("register/", SingupView.as_view(), name='register'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/<slug:slug>/", UserDetail.as_view(), name="user-detail"),
    path("artikel/<slug:slug>/", ArtikelDetail.as_view(), name="detail-artikel"),
    path("list/", ArtikelViewList.as_view(), name="list-artikel"),
    path("edit/", edit, name="edit"),
    path("create/", artikelform, name="artikel-form"),
    path("search/", SearchView.as_view(), name="search"),
    path("chat/", chat, name="chat"),
    path("", ArtikelView.as_view(), name="home"),
    path("<slug:slug>/like/", ArtikelLike.as_view(), name="like-artikel"),
    path("api/<slug:slug>/like/", ArtikelLikeApi.as_view(), name="like-artikel-api"),
    path("tags/<slug:slug>/", list_post_tags, name="tags-list"),
    path("password/change/", auth_views.PasswordChangeView.as_view(template_name="change_password.html"), name="change_password")
]

templates/include/navbar.html
<div>
    <header id="header">
   <div class="flex bg-white border-b border-gray-200 fixed top-0 inset-x-0 h-16 items-center" style="z-index: 100;">
       <div class="w-full max-w-screen-xl relative mx-auto px-6">
           <div class="flex items-center -mx-6">
               <div class="lg:w-1/4 xl:w-1/5 pl-6 pr-6 lg:pr-8">
                   <div class="flex items-center">
                       <a href="{% url 'base:home' %}" class="block lg:mr-4 lg:ml-8">
                           <svg class="h-10 w-auto hidden md:block" height="72" viewBox="0 0 128 128" width="72" xmlns="http://www.w3.org/2000/svg"><g><g><path d="m64 78.38v28.75l-24.896 14.37-24.897-14.37v-28.75l24.897-14.38z" fill="#fd637b"/><path d="m39.1 92.75v28.75l-24.89-14.37v-28.75z" fill="#62e0da"/><path d="m64 78.38v28.75l-24.9 14.37v-28.75z" fill="#fdd82e"/></g><g><path d="m64 20.88v28.75l-24.896 14.37-24.897-14.37v-28.75l24.897-14.38z" fill="#62e0da"/><path d="m39.1 35.25v28.75l-24.89-14.37v-28.75z" fill="#fdd82e"/><path d="m64 20.88v28.75l-24.9 14.37v-28.75z" fill="#fd637b"/></g><g><path d="m113.793 49.63v28.75l-24.897 14.37-24.896-14.37v-28.75l24.896-14.38z" fill="#fdd82e"/><path d="m113.79 49.63v28.75l-24.89 14.37v-28.75z" fill="#fd637b"/><path d="m88.9 64v28.75l-24.9-14.37v-28.75z" fill="#62e0da"/></g></g></svg>
                       </a>
                       <div>
                            <button id="userButton" class="block lg:mr-4 ml-24">
                                <svg height="43" viewBox="0 -52 512 512" width="43" xmlns="http://www.w3.org/2000/svg"><path d="m0 0h113.292969v113.292969h-113.292969zm0 0" fill="#62e0da"/><path d="m149.296875 0h362.703125v113.292969h-362.703125zm0 0" fill="#fd637b"/><path fill="#62e0da" d="m0 147.007812h113.292969v113.292969h-113.292969zm0 0"/><path fill="#fdd82e" d="m149.296875 147.007812h362.703125v113.292969h-362.703125zm0 0"/><path d="m0 294.011719h113.292969v113.296875h-113.292969zm0 0" fill="#fd637b"/><path fill="#62e0da" d="m149.296875 294.011719h362.703125v113.296875h-362.703125zm0 0"/></svg>
                        </button>
                        <div id="userMenu" class="bg-white  rounded shadow-md absolute mt-4 overflow-auto z-30 invisible px-4 py-4" style="width: 82%; height: 10rem;">
                            <ul class="list-reset flex leading-snug break-all">
                                {% for tag in tagss.all %}
                                <a href="{{tag.get_absolute_url}}">
                                <p class="px-4 py-2 block text-gray-900 hover:bg-gray-400 no-underline hover:no-underline">{{tag.title}}</p>
                                </a>
                                {% endfor %}
                            </ul>
                        </div>
                        </div>
                   </div>
               </div>
               <div class="flex justify-center flex-grow lg:w-5/6 xl:w-11/12">   
                <form method="GET" action="{% url 'base:search' %}">{% csrf_token %}
                    <div class="w-full lg:px-6 xl:px-12">
                        <div class="relative">
                            <span class="algolia-autocomplete">
                                <input class="transition-colors duration-100 ease-in-out focus:outline-0
                                border border-transparent focus:bg-white focus:border-gray-400 placeholder-gray-600
                                rounded-lg bg-gray-200 py-2 pr-4 pl-10 block appearance-none leading-normal ds-input relative" 
                                type="text" name="q" style="width: 34rem;" placeholder="Search the docs Press to focus"/>
                            </span>
                            <div class="pointer-events-none absolute inset-y-0 left-0 pl-4 flex items-center">
                                <svg class="fill-current pointer-events-none text-gray-600 w-4 h-4" id="Capa_1" height="512" viewBox="0 0 515.558 515.558" width="512" xmlns="http://www.w3.org/2000/svg"><path d="m378.344 332.78c25.37-34.645 40.545-77.2 40.545-123.333 0-115.484-93.961-209.445-209.445-209.445s-209.444 93.961-209.444 209.445 93.961 209.445 209.445 209.445c46.133 0 88.692-15.177 123.337-40.547l137.212 137.212 45.564-45.564c0-.001-137.214-137.213-137.214-137.213zm-168.899 21.667c-79.958 0-145-65.042-145-145s65.042-145 145-145 145 65.042 145 145-65.043 145-145 145z"/></svg>
                            </div>
                        </div>
                    </div>
                </form>
                   <button type="button" class="flex px-6 items-center lg:hidden text-gray-500 focus:outline-none focus:text-gray-700">
                       <svg class="fill-current w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                           <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z">
                           </path>
                       </svg>
                   </button>
                   <button type="button" id="" class="hidden flex px-6 items-center lg:hidden text-gray-500 focus:outline-none focus:text-gray-700">
                       <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" class="fill-current w-4 h-4">
                           <path d="M10 8.586L2.929 1.515 1.515 2.929 8.586 10l-7.071 7.071 1.414 1.414L10 11.414l7.071 7.071 1.414-1.414L11.414 10l7.071-7.071-1.414-1.414L10 8.586z">
                           </path>
                       </svg>
                   </button>
                   
               </div>
               {% if user.is_authenticated %}
               <div class="hidden lg:flex lg:items-center xl:w-1/4 px-4">
                <div class="relative mr-12">
                <a href="{% url 'base:chat' %}">
                    <svg class="fill-current w-8 h-8" version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                        width="30.57px" height="30.571px" viewBox="0 0 30.57 30.571" style="enable-background:new 0 0 30.57 30.571;"
                        xml:space="preserve">
                    <g>
                        <g>
                    <path fill="#fd637b" d="M28.412,9.697H27.57v9.255c0,1.441-0.838,2.745-2.521,2.745H8.57v0.44c0,1.274,1.449,2.56,2.937,2.56h12.601l4.819,2.834
                        l-0.7-2.834h0.186c1.486,0,2.158-1.284,2.158-2.56V11.894C30.57,10.62,29.898,9.697,28.412,9.697z"/>
                    <path fill="#62e0da" d="M8.76,20.04h14.002c1.684,0,3.238-1.021,3.238-2.462V8.192V5.978c0-1.442-1.555-2.938-3.238-2.938H3.622
                        C1.938,3.04,0,4.536,0,5.978v11.6c0,1.328,1.642,2.287,3.217,2.435l-1.025,3.891L8.76,20.04z M2,5.978
                        C2.081,5.727,2.925,5.04,3.622,5.04h19.14C23.411,5.04,24,5.715,24,5.978v11.6c-0.048,0.114-0.508,0.462-1.238,0.462H3.622
                        c-0.747,0-1.43-0.35-1.622-0.57V5.978z"/>
                    </g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    <g>
                    </g>
                    </svg>
                </a>
                </div>
                <div class="justify-start items-center text-gray-500">
                    <a href="{{request.user.get_absolute_url}}" class="flex overflow-hidden focus:outline-none focus:border-purple-600 flex-row items-center focus:outline-none focus:shadow-outline rounded-lg">
                        <img class="rounded-full h-8 w-8 object-cover" src="{{ request.user.image_profile.url }}" alt="">
                    </a>
                </div>
                
               </div>
               
               {% else %}
                <div class="mr-4">
                    <a href="{% url 'base:login' %}">
                    <button class="border-2 border-purple-800 text-gray-600 hover:bg-pink-700 hover:text-white font-bold py-2 px-4 rounded">
                        Login
                    </button>
                    </a>
                </div>
                <a href="{% url 'base:register' %}">
                    <button class="border-2 border-purple-800 text-gray-600 hover:bg-pink-700 hover:text-white font-bold py-2 px-4 rounded">
                        Register
                    </button>
                    </a>
                {% endif %}
           </div>
       </div>
   </div>
</header>
</div>
